services:
  postgres:
    hostname: postgres
    image: postgres:18-alpine
    container_name: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: eventbus_dev

  redis:
    hostname: redis
    image: eqalpha/keydb
    container_name: redis
    healthcheck:
      test: keydb-cli ping
    ports:
      - "6379:6379"

  test:
    image: 84codes/crystal:latest-alpine
    volumes:
      - ${PWD}/db:/app/db
      - ${PWD}/src:/app/src
      - ${PWD}/lib:/app/lib
      - ${PWD}/spec:/app/spec
      - ${PWD}/shard.override.yml:/app/shard.override.yml
      - ${PWD}/shard.yml:/app/shard.yml
      - ${PWD}/.ameba.yml:/app/.ameba.yml
      - ${PWD}/views:/app/views
      - ${PWD}/www:/app/www
      # - ${PWD}/.env.example:/app/.env
    depends_on:
      - postgres
      - redis
    environment:
      GITHUB_ACTION: ${GITHUB_ACTION:-}
      PG_DATABASE_URL: postgresql://postgres:password@postgres:5432/eventbus_dev
      REDIS_URL: redis://redis:6379
      # LOG_LEVEL: DEBUG
    working_dir: /app
    entrypoint: ["crystal", "spec", "-v", "--error-trace"]
